# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 10
  - name: LinkedIn
    url: https://www.linkedin.com/in/steven-zgaljic-92340770/
    weight: 20    
  - name: Jahnel Group
    url: /#jahnel-group
    weight: 30
  - name: Blog
    url: https://insights.jahnelgroup.com
    weight: 40